# Generated by Django 4.2 on 2024-11-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=30, verbose_name='телефон')),
                ('email', models.EmailField(max_length=155, verbose_name='Email')),
                ('slug', models.SlugField(max_length=255, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_size', models.CharField(blank=True, max_length=4, verbose_name='размер футболки')),
                ('status', models.CharField(max_length=2, verbose_name='статус клиента')),
                ('nutrition_features', models.CharField(blank=True, max_length=400, verbose_name='питание')),
                ('comment', models.CharField(blank=True, max_length=600, verbose_name='коммент')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='город')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='clients.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PS', 'Паспорт'), ('CR', 'свидетельство')], max_length=2, verbose_name='Тип документа')),
                ('series', models.CharField(max_length=20, verbose_name='Серия документа')),
                ('number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(max_length=400, verbose_name='Кем выдан')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_document', to='clients.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Документ клиента',
                'verbose_name_plural': 'Документы клиентов',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'last_name', 'phone'], name='clients_cli_email_c407c6_idx'),
        ),
    ]
